// ⚚ 2023年安徽中考真题追加包
// 自动追加到 SUBJECTS 各科

(function() {
if (typeof SUBJECTS === 'undefined') return;

// ═══ 数学 2023真题 ═══
SUBJECTS.math.questions.push(
  { id:'m26', kp:'数与式', type:'choice', difficulty:'easy',
    text:'-5的相反数是（  ）',
    options:['5','-5','1/5','-1/5'], answer:'A',
    explanation:'只有符号不同的两个数互为相反数，-5的相反数是5。', source:'2023安徽中考第1题' },
  { id:'m27', kp:'数与式', type:'choice', difficulty:'easy',
    text:'下列计算正确的是（  ）',
    options:['a⁴+a⁴=a⁸','a⁴·a⁴=a¹⁶','(a⁴)⁴=a¹⁶','a⁸÷a⁴=a²'], answer:'C',
    explanation:'(a⁴)⁴=a¹⁶正确。A应为2a⁴，B应为a⁸，D应为a⁴。幂的乘方：底数不变指数相乘。', source:'2023安徽中考第3题' },
  { id:'m28', kp:'数与式', type:'fill', difficulty:'easy',
    text:'计算：∛8 + 1 = ____。', options:null, answer:'3',
    explanation:'∛8=2（2³=8），2+1=3。', source:'2023安徽中考第11题' },
  { id:'m29', kp:'数与式', type:'fill', difficulty:'easy',
    text:'2023年第一季度安徽省采矿业实现利润总额74.5亿元，用科学记数法表示为____。', options:null, answer:'7.45×10⁹',
    explanation:'74.5亿=7,450,000,000=7.45×10⁹。', source:'2023安徽中考第12题' },
  { id:'m30', kp:'数与式', type:'solution', difficulty:'medium',
    text:'先化简再求值：(x²+2x+1)/(x+1)，其中x=√2-1。', options:null,
    answer:'√2',
    explanation:'原式=(x+1)²/(x+1)=x+1，代入x=√2-1得√2。', source:'2023安徽中考第15题' },
  { id:'m31', kp:'方程与不等式', type:'choice', difficulty:'easy',
    text:'在数轴上表示不等式(x-1)/2<0的解集正确的是（  ）',
    options:['x<1','x>1','x<3','x>3'], answer:'A',
    explanation:'解不等式：x-1<0，x<1。', source:'2023安徽中考第4题' },
  { id:'m32', kp:'方程与不等式', type:'solution', difficulty:'medium',
    text:'某商品在甲、乙两地销售单价调整：甲地上涨10%，乙地降价5元。调整前甲地比乙地少10元，调整后甲地比乙地少1元。求调整前甲、乙两地销售单价。', options:null,
    answer:'甲地40元，乙地50元',
    explanation:'设甲x乙y：y-x=10，(y-5)-1.1x=1。解得x=40，y=50。', source:'2023安徽中考第16题' },
  { id:'m33', kp:'一次函数', type:'choice', difficulty:'easy',
    text:'下列函数中，y随x增大而减小的是（  ）',
    options:['y=x²+1','y=-x²+1','y=2x+1','y=-2x+1'], answer:'D',
    explanation:'一次函数y=kx+b中k<0时y随x增大而减小，只有D的k=-2<0。', source:'2023安徽中考第5题' },
  { id:'m34', kp:'二次函数', type:'solution', difficulty:'hard',
    text:'抛物线y=ax²+bx-3过点A(3,12)，对称轴x=2。(1)求a,b；(2)已知B(t,?),C(t+1,?)在抛物线上(对称轴右侧)，过B,C作x轴垂线交直线OA于D,E。(ⅰ)t=2时求△OBD与△OCE面积和；(ⅱ)是否存在B使B,C,D,E四边形面积为7/2？', options:null,
    answer:'(1)a=3,b=-12;(2)(ⅰ)7/2;(ⅱ)存在，t=5/2',
    explanation:'由条件得-b/2a=2且9a+3b-3=12→a=3,b=-12。抛物线y=3x²-12x-3。OA:y=4x。代入计算。', source:'2023安徽中考第23题压轴' },
  { id:'m35', kp:'三角形', type:'fill', difficulty:'medium',
    text:'清初数学家梅文鼎证"三斜求积术"：锐角△ABC中AD是高，BD=(1/2)(AB+(BC²-AC²)/AB)。当AB=7,BC=6,AC=5时，CD=____。', options:null, answer:'1',
    explanation:'BD=(1/2)(7+(36-25)/7)=(1/2)(7+11/7)=5，CD=BC-BD=6-5=1。', source:'2023安徽中考第13题' },
  { id:'m36', kp:'三角形', type:'solution', difficulty:'hard',
    text:'Rt△ABC中M是斜边AB中点，MA绕M旋转至MD(D在AB外)。(1)求∠ADB；(2)已知D和AC上点E满足ME⊥AD,DE∥AB。(ⅰ)证BD=AD；(ⅱ)若AC=8,BC=6求tan∠ABE。', options:null,
    answer:'(1)90°;(2)(ⅰ)见解析;(ⅱ)3/4',
    explanation:'(1)MA=MD=MB→A、D、B在以M为圆心圆上，AB为直径→∠ADB=90°。(2)构造菱形等证明。', source:'2023安徽中考第22题' },
  { id:'m37', kp:'四边形', type:'choice', difficulty:'hard',
    text:'正方形ABCD中E在AC上，EF⊥AB于F，DE延长交BC于M交AB延长线于G。AF=2,FB=1，则MG=（  ）',
    options:['2√3','3√5/2','5/2','√10'], answer:'B',
    explanation:'利用相似三角形和平行线分线段成比例求解。', source:'2023安徽中考第8题' },
  { id:'m38', kp:'圆', type:'choice', difficulty:'medium',
    text:'正五边形ABCDE内接于⊙O，连接OC、OD，则∠BAE-∠COD=（  ）',
    options:['60°','54°','48°','36°'], answer:'D',
    explanation:'正五边形内角∠BAE=108°，中心角∠COD=360°/5=72°，差为36°。', source:'2023安徽中考第6题' },
  { id:'m39', kp:'统计与概率', type:'choice', difficulty:'medium',
    text:'三位数中任意相邻数字之差绝对值≤1称"平稳数"。用1,2,3随机组成无重复数字三位数，恰好是平稳数的概率为（  ）',
    options:['1/2','1/3','2/3','4/9'], answer:'B',
    explanation:'123,132,213,231,312,321共6种排列。平稳数有123(1-2≤1,2-3≤1)和321(|3-2|=1,|2-1|=1)。P=2/6=1/3。', source:'2023安徽中考第7题' },
  { id:'m40', kp:'统计与概率', type:'solution', difficulty:'medium',
    text:'七、八年级各抽10名学生"包粽子"实践活动评分（6-10分）。八年级中位数8.5分。(1)七年级7分人数____，众数____；(2)a=____b=____；(3)优秀率高的年级是否平均成绩也高？', options:null,
    answer:'(1)1人,8分;(2)a=2,b=3;(3)不是——八年级优秀率50%但均分8.25，七年级优秀率20%但均分8.3',
    explanation:'优秀率≠平均分，需根据频数分布计算验证。', source:'2023安徽中考第21题' },
  { id:'m41', kp:'规律探索', type:'solution', difficulty:'medium',
    text:'图案规律：第1个"●"3个，"★"1=1×2/2个；第2个"●"6个，"★"3=2×3/2个...(1)第n个"●"个数____；(2)第n个"★"个数____；(3)求n使1+2+...+n等于第n个"●"的2倍。', options:null,
    answer:'(1)3n;(2)n(n+1)/2;(3)n=11',
    explanation:'n(n+1)/2=2×3n→n²+n=12n→n=11（n≠0）。', source:'2023安徽中考第18题' },
  { id:'m42', kp:'三角形', type:'solution', difficulty:'medium',
    text:'无人机从A点竖直上升到C时，C到B距离40m，B俯角24.2°；继续上升到D，B俯角36.9°。求CD上升高度。(sin24.2°≈0.41,cos24.2°≈0.91,tan24.2°≈0.45,sin36.9°≈0.60,cos36.9°≈0.80,tan36.9°≈0.75)', options:null,
    answer:'约10.9m',
    explanation:'Rt△ABC:AC=40×0.41=16.4,AB=40×0.91=36.4。Rt△ABD:AD=36.4×0.75=27.3。CD=27.3-16.4=10.9m。', source:'2023安徽中考第19题' }
);

// ═══ 物理 2023真题 ═══
SUBJECTS.physics.questions.push(
  { id:'p26', kp:'声现象', type:'fill', difficulty:'easy',
    text:'古代乐师调整琴弦的长度，主要是为了改变乐音的____。', options:null, answer:'音调',
    explanation:'调整弦长改变振动频率→音调变化。弦越短频率越高音调越高。', source:'2023安徽中考第2题' },
  { id:'p27', kp:'力学基础', type:'fill', difficulty:'easy',
    text:'北斗导航卫星进入地球同步轨道后，以地面为参照物卫星静止，以太阳为参照物卫星运动。这说明运动和静止是____的。', options:null, answer:'相对',
    explanation:'同一物体选不同参照物运动状态不同→运动和静止是相对的。', source:'2023安徽中考第1题' },
  { id:'p28', kp:'力学基础', type:'fill', difficulty:'easy',
    text:'射箭时运动员释放弓弦将箭射出，弓弦的____能转化为箭的动能。', options:null, answer:'弹性势',
    explanation:'拉开的弓弦发生弹性形变具有弹性势能，释放时转化为箭的动能。', source:'2023安徽中考第4题' },
  { id:'p29', kp:'力学基础', type:'choice', difficulty:'medium',
    text:'汽车配有安全带和头枕。向前行驶的汽车突然加速、紧急刹车时，分别起主要保护作用的是（  ）',
    options:['头枕、头枕','安全带、安全带','安全带、头枕','头枕、安全带'], answer:'D',
    explanation:'突然加速→人后仰→头枕保护。紧急刹车→人前倾→安全带保护。', source:'2023安徽中考第12题' },
  { id:'p30', kp:'压强浮力', type:'fill', difficulty:'medium',
    text:'“奋斗者”号潜至海面下10000m深处，其外部0.1m²水平舱面所受海水压力约为____N。(ρ海水=1×10³kg/m³,g=10N/kg)', options:null, answer:'1×10⁷',
    explanation:'p=ρgh=1×10³×10×10000=1×10⁸Pa，F=pS=1×10⁸×0.1=1×10⁷N。', source:'2023安徽中考第5题' },
  { id:'p31', kp:'简单机械', type:'fill', difficulty:'medium',
    text:'爸爸和小红坐跷跷板两侧水平平衡，小红质量15kg力臂1.2m，爸爸力臂0.3m，爸爸质量____kg。', options:null, answer:'60',
    explanation:'杠杆平衡：m₁gL₁=m₂gL₂→m₁=15×1.2/0.3=60kg。', source:'2023安徽中考第6题' },
  { id:'p32', kp:'简单机械', type:'solution', difficulty:'medium',
    text:'斜面：重6N物体沿斜面向上匀速拉动0.6m，上升高度0.3m，弹簧测力计示数4N。求：(1)有用功；(2)机械效率。', options:null, answer:'(1)1.8J;(2)75%',
    explanation:'W有=Gh=6×0.3=1.8J。W总=Fs=4×0.6=2.4J。η=1.8/2.4=75%。', source:'2023安徽中考第21题' },
  { id:'p33', kp:'电路基础', type:'fill', difficulty:'medium',
    text:'电路R₀=12Ω。S₂掷a端电压表2.5V，掷b端电压表1.5V，则Rx=____Ω。', options:null, answer:'8',
    explanation:'掷a测电源U=2.5V，掷b测R₀电压U₀=1.5V→Ux=1V。串联I相等：1.5/12=1/Rx→Rx=8Ω。', source:'2023安徽中考第10题' },
  { id:'p34', kp:'电路基础', type:'choice', difficulty:'medium',
    text:'应变片中金属丝被拉长变细导致电阻变大，则电路中（  ）',
    options:['电压表和电流表示数都变大','电压表示数变小电流表示数变大','电压表和电流表示数都变小','电压表示数变大电流表示数变小'], answer:'D',
    explanation:'R金属↑→R总↑→I↓→电流表示数↓。应变片分压↑→电压表示数↑。', source:'2023安徽中考第16题' },
  { id:'p35', kp:'电功率', type:'fill', difficulty:'medium',
    text:'汽车尾挡风玻璃电除雾装置：5条阻值均为12Ω电阻丝并联，接12V汽车电池，工作1min产生总热量____J。', options:null, answer:'3600',
    explanation:'I单=12/12=1A，I总=5A，P=UI=12×5=60W，Q=W=Pt=60×60=3600J。', source:'2023安徽中考第9题' },
  { id:'p36', kp:'电与磁', type:'fill', difficulty:'easy',
    text:'探究产生感应电流条件实验：导体AB不动，磁体沿图示方向运动，闭合回路中____（能/不能）产生感应电流。', options:null, answer:'能',
    explanation:'产生感应电流条件：闭合回路部分导体切割磁感线。导体不动磁体运动→相对运动→切割磁感线→有感应电流。', source:'2023安徽中考第7题' },
  { id:'p37', kp:'电与磁', type:'choice', difficulty:'medium',
    text:'电动机原理图，线圈abcd从O点沿转轴观察顺时针转动。若电源正负极对调，则（  ）',
    options:['F端为N极P端为N极','F端为S极P端为S极','线圈仍顺时针转动','线圈将逆时针转动'], answer:'C',
    explanation:'电源正负极对调→磁场方向反+电流方向反→线圈受力方向不变→仍顺时针转。', source:'2023安徽中考第17题' },
  { id:'p38', kp:'力学基础', type:'choice', difficulty:'medium',
    text:'玻璃棒与丝绸摩擦后玻璃棒带正电、丝绸带负电。摩擦过程中（  ）',
    options:['玻璃棒和丝绸都得到电子','玻璃棒和丝绸都失去电子','玻璃棒失去电子丝绸得到电子','玻璃棒得到电子丝绸失去电子'], answer:'C',
    explanation:'玻璃棒束缚电子能力弱→电子从玻璃棒转移到丝绸→玻璃棒失电子带正电，丝绸得电子带负电。', source:'2023安徽中考第11题' },
  { id:'p39', kp:'声现象', type:'choice', difficulty:'medium',
    text:'身高测量仪：感应器距测高台2.5m，信号从发射到接收经历5×10⁻³s，声速340m/s。该同学身高为（  ）',
    options:['1.70m','1.65m','0.85m','0.80m'], answer:'B',
    explanation:'超声波往返距离=½×340×0.005=0.85m（头顶到感应器）。身高=2.5-0.85=1.65m。', source:'2023安徽中考第14题' },
  { id:'p40', kp:'电功率', type:'solution', difficulty:'medium',
    text:'电热水壶：1kg水通电210s从20℃升到70℃。c水=4.2×10³。(1)水吸收热量；(2)若产热全被水吸收估测电功率；(3)估测值偏大还是偏小？', options:null,
    answer:'(1)2.1×10⁵J;(2)1000W;(3)偏小——实际有热量损失',
    explanation:'Q=cmΔt=4.2×10³×1×50=2.1×10⁵J。P=Q/t=2.1×10⁵/210=1000W。热量损失→实际功率更大→估测偏小。', source:'2023安徽中考第22题' }
);

// ═══ 化学 2023真题 ═══
SUBJECTS.chemistry.questions.push(
  { id:'c23', kp:'化学与生活', type:'choice', difficulty:'easy',
    text:'下列有关"油、盐、酱、醋"的说法，错误的是（  ）',
    options:['油脂是人体唯一的供能物质','食盐中的钠是人体必需元素','铁强化酱油可补充铁元素','食醋有酸味主要因含醋酸'], answer:'A',
    explanation:'糖类、油脂和蛋白质都是供能物质，油脂不是唯一的。', source:'2023安徽中考第1题' },
  { id:'c24', kp:'化学与生活', type:'choice', difficulty:'easy',
    text:'不利于人类发展与环境保护的是（  ）',
    options:['提高废弃塑料回收利用','长期大量施用同种磷肥','加快CO₂资源化利用研究','污水分级处理后再利用'], answer:'B',
    explanation:'长期大量施用同种磷肥会造成土壤和水体污染。', source:'2023安徽中考第2题' },
  { id:'c25', kp:'金属', type:'choice', difficulty:'easy',
    text:'关于镁元素，说法正确的是（  ）',
    options:['镁燃烧产生明亮光可用于照明弹','2Mg表示两个镁元素','镁原子核外电子数为24','镁原子质量=24.31×碳12原子质量'], answer:'A',
    explanation:'B错：2Mg表示两个镁原子。C错：镁原子序数12电子数12。D错：相对原子质量定义不同。', source:'2023安徽中考第3题' },
  { id:'c26', kp:'化学与生活', type:'choice', difficulty:'medium',
    text:'大马酮(C₁₃H₁₈O)是玫瑰香味的来源。说法正确的是（  ）',
    options:['一个分子含9个H₂','碳氢质量比为13:18','属于无机物','分子在不断运动'], answer:'D',
    explanation:'闻到香味说明分子在运动。分子中不含分子(A错)，质量比需计算(B错)，含碳有机物(C错)。', source:'2023安徽中考第4题' },
  { id:'c27', kp:'实验探究', type:'choice', difficulty:'medium',
    text:'配制10%NaOH溶液的部分操作，正确的是（  ）',
    options:['取用NaOH瓶塞未倒放','称量NaOH用纸片垫放','量取水时瓶口紧挨量筒口标签向手心','读取水体积时仰视'], answer:'C',
    explanation:'倾倒液体时标签向手心防腐蚀标签。A瓶塞应倒放，BNaOH有腐蚀性应用玻璃器皿，D读数应平视。', source:'2023安徽中考第6题' },
  { id:'c28', kp:'酸碱盐', type:'choice', difficulty:'medium',
    text:'关于硫酸的说法，错误的是（  ）',
    options:['稀硫酸和锌反应制氢气','含硫酸废液可用熟石灰中和','稀硫酸密度比水小','蘸取浓硫酸的木棍会变黑'], answer:'C',
    explanation:'稀硫酸密度比水大，不是比水小。浓硫酸有脱水性使木棍炭化变黑。', source:'2023安徽中考第7题' },
  { id:'c29', kp:'化学与生活', type:'choice', difficulty:'medium',
    text:'物质用途与性质没有关联的是（  ）',
    options:['石墨-可燃-作电极','生石灰-与水反应放热-自热盒饭','活性炭-吸附性强-消除异味','合成纤维-强度高弹性好-织布料'], answer:'A',
    explanation:'石墨作电极利用导电性而非可燃性，性质用途无关联。', source:'2023安徽中考第8题' },
  { id:'c30', kp:'物质变化', type:'choice', difficulty:'medium',
    text:'口罩熔喷布原料Z由X制备，微观示意图如下。说法正确的是（  ）',
    options:['X化学式为C₃H₆','反应前后分子种类不变','Y、Z在O₂中充分燃烧产物相同','反应前后原子个数不变'], answer:'D',
    explanation:'质量守恒定律→反应前后原子种类和个数不变。A错C₃H₈，B错反应前后分子种类必变，C错产物不同。', source:'2023安徽中考第9题' },
  { id:'c31', kp:'实验探究', type:'choice', difficulty:'medium',
    text:'用如图装置探究磷燃烧条件，说法错误的是（  ）',
    options:['实验室可通过加热KMnO₄制取O₂','通O₂后白磷燃烧说明燃烧只需要O₂','红磷不燃白磷燃烧说明白磷着火点比红磷低','少量白磷可保存在冷水中'], answer:'B',
    explanation:'燃烧需三个条件同时满足：可燃物+O₂+温度达着火点。B只强调O₂忽略了温度条件。', source:'2023安徽中考第10题' },
  { id:'c32', kp:'物质变化', type:'choice', difficulty:'medium',
    text:'钠与氯气反应生成氯化钠。说法正确的是（  ）',
    options:['氯化钠固体由分子构成','钠原子失去一个电子形成稳定结构','氯原子核外有两个电子层','Cl生成Cl⁻证明元素种类改变'], answer:'B',
    explanation:'Na最外层1个电子→失去→Na⁺稳定结构。NaCl由离子构成，Cl有3层电子，元素种类不变。', source:'2023安徽中考第11题' },
  { id:'c33', kp:'水与溶液', type:'choice', difficulty:'hard',
    text:'煤化工废水含NaCl、Na₂SO₄、NaNO₃，其溶解度曲线如图。说法正确的是（  ）',
    options:['NaCl更适合降温结晶','a₁℃时NaNO₃饱和溶液溶质质量分数80%','a₂℃时NaCl和Na₂SO₄饱和溶液溶质质量分数相等','40℃Na₂SO₄饱和溶液升温到60℃变不饱和'], answer:'C',
    explanation:'a₂℃时两物质溶解度相等→饱和溶液溶质质量分数相等。NaCl适合蒸发结晶，a₁℃时ω=80/180≈44.4%，40→60℃Na₂SO₄溶解度减小仍饱和。', source:'2023安徽中考第12题' },
  { id:'c34', kp:'实验探究', type:'solution', difficulty:'hard',
    text:'草酸钙分解：CaC₂O₄→加热→CaCO₃+CO↑+CO₂↑。验证产物既有CO又有CO₂。(1)B中现象____，D中方程式____；(2)Fe₂O₃中铁化合价____；(3)不加B可否验证CO存在？(4)实验不足？', options:null,
    answer:'(1)石灰水变浑浊；3CO+Fe₂O₃→高温→2Fe+3CO₂；(2)+3；(3)可以——D中红棕色变黑也说明CO存在；(4)缺少尾气处理装置',
    explanation:'CO有还原性使Fe₂O₃变Fe（红棕→黑）。CO有毒需尾气处理。', source:'2023安徽中考第14题' },
  { id:'c35', kp:'酸碱盐', type:'solution', difficulty:'medium',
    text:'活性氧化铜制备：(1)步骤①CuO+2HCl=____；(2)说法正确的是____(填字母)；(3)步骤②加Na₂CO₃有气泡原因____；(4)步骤③反应类型____。', options:null,
    answer:'(1)CuCl₂+H₂O;(2)BD;(3)步骤①盐酸过量，与Na₂CO₃反应生成CO₂;(4)分解反应',
    explanation:'过滤时玻璃棒用于引流非搅拌(A错)；Cu₂(OH)₂CO₃难溶于水(C错)。碱式碳酸铜受热分解→分解反应。', source:'2023安徽中考第15题' },
  { id:'c36', kp:'实验探究', type:'solution', difficulty:'hard',
    text:'铁锈蚀探究：(1)铁与稀盐酸方程式____；(2)铁锈颜色____；(3)B中煮沸蒸馏水目的____；(4)对比ABD说明铁锈蚀需要____；C比D锈蚀更严重原因____。', options:null,
    answer:'(1)Fe+2HCl=FeCl₂+H₂↑;(2)红褐色;(3)除去水中溶解的O₂;(4)氧气和水；C中试管敞口铁钉与O₂和水充分接触',
    explanation:'铁锈蚀是铁与O₂和H₂O共同作用的结果。控制变量法逐一排除。', source:'2023安徽中考第16题' },
  { id:'c37', kp:'化学与生活', type:'solution', difficulty:'medium',
    text:'过氧化尿素UP(CO(NH₂)₂·H₂O₂,M=94)：2UP→2CO(NH₂)₂+2H₂O+O₂↑。100g洗涤剂加MnO₂产生0.32g O₂。求UP质量分数。', options:null,
    answer:'1.88%',
    explanation:'2×94g UP→32g O₂。设UP质量为x：x/0.32=188/32→x=1.88g。ω=1.88/100=1.88%。', source:'2023安徽中考第17题' }
);

// ═══ 道德与法治 2023真题 ═══
SUBJECTS.politics.questions.push(
  { id:'z27', kp:'成长与自我', type:'choice', difficulty:'easy',
    text:'在"探问生命"主题班会上，通过"我的自画像"活动看到自己独一无二。这体现了（  ）',
    options:['生命是独特的','生命是短暂的','生命是不可逆的','生命来之不易'], answer:'A',
    explanation:'"独一无二"→生命是独特的，每个人的生命都具有不可替代性。', source:'2023安徽中考第2题' },
  { id:'z28', kp:'友谊与交往', type:'choice', difficulty:'easy',
    text:'下列诗句体现亲情的是（  ）',
    options:['莫愁前路无知己天下谁人不识君','接天蓬叶无穷碧映日荷花别样红','春蚕到死丝方尽蜡炬成灰泪始干','独在异乡为异客每逢佳节倍思亲'], answer:'D',
    explanation:'"每逢佳节倍思亲"→对亲人的思念→亲情。A友情，B写景，C奉献精神。', source:'2023安徽中考第3题' },
  { id:'z29', kp:'青春与情绪', type:'choice', difficulty:'medium',
    text:'老师在班级放置"烦恼盒"让学生倾诉情绪并帮助解决烦恼。这表明（  ）\n①学生成长离不开老师指导 ②学生烦恼只有老师才能解决 ③学生发展取决于老师理念 ④情绪可通过适当方式调节',
    options:['①②','①④','②③','③④'], answer:'B',
    explanation:'②③中"只有""取决于"绝对化错误。①④正确——老师指导学生成长，情绪可调节。', source:'2023安徽中考第4题' },
  { id:'z30', kp:'文化与自信', type:'choice', difficulty:'medium',
    text:'某村开展道德模范评选传播"好人"精神，促进了乡风文明。这说明（  ）\n①核心价值观需人人践行 ②学好榜样利于构建和谐社会 ③崇德向善需共同营造 ④典型评选决定社会道德环境',
    options:['①②③','①②④','①③④','②③④'], answer:'A',
    explanation:'④"决定"夸大了评选活动作用，排除。①②③正确。', source:'2023安徽中考第5题' },
  { id:'z31', kp:'创新与发展', type:'choice', difficulty:'medium',
    text:'科普工作从说教式向体验式转变（  ）\n①能让青少年窥见科学神奇 ②能杜绝重理论轻实践 ③有助于激发创造热情 ④有利于引导青少年热爱科技',
    options:['①②③','①②④','①③④','②③④'], answer:'C',
    explanation:'②"杜绝"绝对化。①③④正确。', source:'2023安徽中考第6题' },
  { id:'z32', kp:'社会与规则', type:'choice', difficulty:'medium',
    text:'让"吃播"节目具有正能量需要（  ）\n①网络平台加强内容审核 ②企业提高网速 ③行政机关依法行政加强监管 ④网络参与者恪守道德守法',
    options:['①②③','①②④','①③④','②③④'], answer:'C',
    explanation:'②提高网速与传播正能量无关。①③④正确。', source:'2023安徽中考第7题' },
  { id:'z33', kp:'集体与法治', type:'choice', difficulty:'medium',
    text:'《民法典》记载了从出生到死亡的各种权利，但若不行使则是"废纸"。这启示我们（  ）',
    options:['只要守程序就能维护权利','行使权利不需要有界限','享受权利不必承担义务','要增强自己的权利意识'], answer:'D',
    explanation:'题干强调权利需积极行使→增强权利意识。ABC均有知识性错误。', source:'2023安徽中考第8题' },
  { id:'z34', kp:'成长与自我', type:'choice', difficulty:'easy',
    text:'漫画提醒我们"用眼1小时望远眺望5分钟"，要（  ）',
    options:['不使用任何电子产品','掌握所有自救方法','关注并守护精神家园','爱护身体养成健康生活方式'], answer:'D',
    explanation:'保护视力→爱护身体→健康生活方式。A、B绝对化错误，C未体现。', source:'2023安徽中考第9题' },
  { id:'z35', kp:'世界与中国', type:'choice', difficulty:'medium',
    text:'十国歌曲在春晚汇聚唱响《一带繁花一路歌》，体现（  ）\n①世界文化多样性 ②每个民族文化独特 ③应全盘吸收外来文化 ④不同文化可交流',
    options:['①②③','①②④','①③④','②③④'], answer:'B',
    explanation:'③"全盘吸收"错误→取其精华去其糟粕。①②④正确。', source:'2023安徽中考第10题' },
  { id:'z36', kp:'国家与制度', type:'choice', difficulty:'medium',
    text:'北京、上海、兰州等不再全面禁止路边摊，这（  ）\n①能活跃经济促进居民增收 ②将推动社会主义市场经济体制建立 ③有利满足人民美好生活需求 ④发挥企业在资源配置中决定作用',
    options:['①②','①③','②④','③④'], answer:'B',
    explanation:'②错误——市场经济体制已建立；④错误——市场（非企业）起决定作用。①③正确。', source:'2023安徽中考第11题' },
  { id:'z37', kp:'世界与中国', type:'choice', difficulty:'medium',
    text:'“中国复眼”探测距离将达1.5亿公里为规避小行星撞击提供技术支撑。体现（  ）\n①中国贡献中国力量 ②中国承担全部责任 ③践行人类命运共同体 ④参与全球治理体系改革',
    options:['①③','①④','②③','②④'], answer:'A',
    explanation:'②"全部责任"过于绝对；④题干未涉及治理体系改革。①③正确。', source:'2023安徽中考第12题' },
  { id:'z38', kp:'文化与自信', type:'solution', difficulty:'medium',
    text:'(1)如何增强革命文物对青少年的吸引力？\n(2)红色旅游对青少年品格塑造有何价值？', options:null,
    answer:'(1)借助VR/AR技术丰富展览形式；开展文物知识科普讲座；讲述文物背后英雄故事。\n(2)增强爱国主义情感；激发正义责任担当意识；树立正确三观。',
    explanation:'革命文物承载红色基因，需要用青少年喜闻乐见的方式传播。', source:'2023安徽中考第14题' },
  { id:'z39', kp:'集体与法治', type:'solution', difficulty:'medium',
    text:'案例：韩某被境外间谍引诱搜集党政机密文件，触犯刑法。判决：间谍罪，有期徒刑11年6个月，剥夺政治权利4年，没收财产5万元。(1)"本院"指哪个国家机关？主刑和附加刑分别是什么？(2)给我们什么警示？', options:null,
    answer:'(1)人民法院。主刑：有期徒刑。附加刑：剥夺政治权利、没收财产。\n(2)犯罪是成长路上最凶险的陷阱；预防犯罪需杜绝不良行为；增强法治观念依法自律。',
    explanation:'考查违法犯罪的分类、刑罚种类和预防犯罪。', source:'2023安徽中考第15题' },
  { id:'z40', kp:'国家与制度', type:'solution', difficulty:'medium',
    text:'安徽推进民主法治示范村(社区)建设、优化创新环境促进发展、"江豚戏水"再现长江。(1)民主法治示范村建设意义；(2)创新环境优化对经济社会作用；(3)"江豚戏水"对生态文明启示。', options:null,
    answer:'(1)人民群众直接行使民主权利，管理基层公共事务，推动民主建设。\n(2)为高质量发展提供环境；促进产业升级；培育新增长点。\n(3)以资源环境承载力为基础；坚持节约资源保护环境国策；贯彻新发展理念。',
    explanation:'综合考查基层民主、创新驱动、生态文明三大考点。', source:'2023安徽中考第16题' }
);

})();
