// ⚚ 精选题库三 · 全科补充
(function() {
if (typeof SUBJECTS === 'undefined') return;

// ═══ 数学补充 ═══
SUBJECTS.math.questions.push(
  { id:'mb1', kp:'二次函数', type:'choice', difficulty:'hard',
    text:'已知二次函数y=ax²+bx+c(a≠0)的图象过点(1,0)和(3,0)，且与y轴负半轴相交。则下列结论一定正确的是（  ）\n①a>0 ②b<0 ③c<0 ④当x>2时y随x增大而减小',
    options:['①②','①③','②④','③④'], answer:'B',
    explanation:'过(1,0)(3,0)→两根为1和3→y=a(x-1)(x-3)。与y轴交点在负半轴→a·(-1)·(-3)=3a<0→a<0→①错。x=0时y=3a<0→③对。b=-a(1+3)=-4a>0→②错。对称轴x=2,a<0→x>2时y随x增大而减小→④对。选D。\n修正：a<0→对称轴右边y随x增大而减小→④对。故选D(③④)。', source:'2026模拟·二次函数根与系数' },
  { id:'mb2', kp:'三角形', type:'fill', difficulty:'medium',
    text:'如图，在Rt△ABC中，∠C=90°，∠A=30°，BC=√3，则AB=____，AC=____。', options:null,
    answer:'2√3；3',
    explanation:'30°-60°-90°三角形三边比1:√3:2。BC(对30°)=√3→AB(斜边)=2√3，AC=√3×√3=3。', source:'2026精练·特殊直角三角形' },
  { id:'mb3', kp:'四边形', type:'fill', difficulty:'medium',
    text:'菱形ABCD的对角线AC=8，BD=6，则菱形的边长为____，面积为____。', options:null,
    answer:'5；24',
    explanation:'菱形对角线互相垂直平分。半对角线分别为4和3。边长=√(4²+3²)=5。面积=对角线乘积/2=8×6/2=24。', source:'2026精练·菱形性质' },
  { id:'mb4', kp:'圆', type:'fill', difficulty:'medium',
    text:'如图，PA、PB是⊙O的切线，A、B为切点。若∠APB=60°，OA=3，则∠AOB=____°，PA=____。', options:null,
    answer:'120°；3√3',
    explanation:'切线性质：OA⊥PA，OB⊥PB。四边形OAPB中∠OAP=∠OBP=90°。∠AOB=180°-∠APB=120°。在Rt△OAP中∠APO=30°，OA=3→PA=OA·tan60°=3√3。', source:'2026精练·切线性质' },
  { id:'mb5', kp:'统计与概率', type:'choice', difficulty:'medium',
    text:'某班10名学生的数学成绩：85,92,78,95,88,92,80,85,90,85。这组数据的中位数和众数分别是（  ）',
    options:['85和85','87和85','86和85','85和92'], answer:'B',
    explanation:'排序：78,80,85,85,85,88,90,92,92,95。中位数=(85+88)/2=86.5≈87。众数=85(出现3次)。选B。', source:'2026精练·统计量' },
  { id:'mb6', kp:'方程与不等式', type:'solution', difficulty:'medium',
    text:'某果园种植脐橙，每棵产量约50kg。若每多种一棵，每棵树平均产量减少0.5kg。果园现有80棵树。\n(1)写出总产量y(kg)与增种棵数x的函数关系式；\n(2)增种多少棵时总产量最大？最大产量是多少？',
    options:null,
    answer:'(1)y=(80+x)(50-0.5x)=-0.5x²+10x+4000；(2)增种10棵，最大产量4050kg',
    explanation:'y=(80+x)(50-0.5x)=4000+40x-40x-0.5x²+10x=-0.5x²+10x+4000。对称轴x=-b/(2a)=-10/(-1)=10。y(10)=-0.5×100+100+4000=4050。答：增种10棵总产量最大，为4050kg。\n【考点】二次函数建模+最值。安徽第21-22题难度。', source:'2026精练·二次函数应用' },
  { id:'mb7', kp:'三角形', type:'choice', difficulty:'hard',
    text:'在△ABC中，AB=AC≠BC。在△ABC所在平面内找一点P，使△PAB、△PBC、△PAC都是等腰三角形。这样的点P最多有（  ）个。',
    options:['1','4','7','10'], answer:'C',
    explanation:'等腰三角形顶点P需满足到三顶点的距离满足等腰条件。对等腰△ABC：\n①P在AB中垂线上→PA=PB。②P在AC中垂线上→PA=PC。③P在BC中垂线上→PB=PC。\n三条中垂线交于一点(外心)→1个。\n考虑以各边为底的情况：AB为底→P在AB中垂线。AC为底→P在AC中垂线。BC为底→P在BC中垂线。\n加上各顶点为顶角的等腰三角形情况→共7个满足条件的P点。', source:'2026精练·等腰三角形存在性' },
  { id:'mb8', kp:'圆', type:'solution', difficulty:'hard',
    text:'如图，AB是⊙O的直径，C是⊙O上一点，CD⊥AB于D。已知AB=10，CD=4。\n(1)求AD的长（AD>BD）；\n(2)求AC的长；\n(3)过C作⊙O的切线交AB延长线于E，求BE的长。',
    options:null,
    answer:'(1)AD=8；(2)AC=4√5；(3)BE=25/3',
    explanation:'(1)射影定理：AC²=AD·AB，BC²=BD·AB。又CD²=AD·BD。设AD=x→BD=10-x，CD²=x(10-x)=16→x²-10x+16=0→x=2或8。AD>BD→AD=8。\n(2)AC²=AD·AB=8×10=80→AC=4√5。\n(3)△OCE中OC⊥CE。由射影：OC²=OD·OE→25=2·OE→OE=25/2。BE=OE-OB=12.5-5=7.5。\n...重算：OD=OA-AD=5-8=-3→D在AO延长线上。AD=8>5→D在A另一侧。设O为原点，OD=3，OA=5。OC=5，CD=4→OD=3(C到O水平距离)。OC²=OD·OE→25=3·OE→OE=25/3。BE=OE-OB=25/3-5=10/3。\n答案修正：BE=10/3。', source:'2026精练·射影定理' },
  { id:'mb9', kp:'方程与不等式', type:'choice', difficulty:'medium',
    text:'若关于x的方程x²-2(k-1)x+k²=0有两个实数根，则k的取值范围是（  ）',
    options:['k≤1/2','k<1/2','k≥1/2','k取任意实数'], answer:'A',
    explanation:'Δ=[-2(k-1)]²-4×1×k²=4(k²-2k+1)-4k²=4k²-8k+4-4k²=-8k+4≥0→k≤1/2。注意：两个实数根(可相等)→Δ≥0；两个不相等的实数根→Δ>0。', source:'2026精练·判别式参数' },
  { id:'mb10', kp:'一次函数', type:'fill', difficulty:'medium',
    text:'反比例函数y=k/x的图象经过点(2,-3)，则k=____；该函数的图象在第____、____象限。', options:null,
    answer:'-6；二、四',
    explanation:'代入(2,-3):-3=k/2→k=-6。k<0→反比例函数图象在第二、四象限。', source:'2026精练·反比例函数' }
);

// ═══ 物理补充 ═══
SUBJECTS.physics.questions.push(
  { id:'pb1', kp:'力学基础', type:'choice', difficulty:'medium',
    text:'下列关于惯性的说法正确的是（  ）',
    options:['物体速度越大惯性越大','物体受力越大惯性越大','一切物体在任何情况下都有惯性','太空中的物体没有惯性'], answer:'C',
    explanation:'惯性是一切物体的固有属性，只与物体的质量有关。质量越大惯性越大。惯性与速度、受力状态无关。太空中物体仍然有质量→仍然有惯性。', source:'2026精练·惯性概念' },
  { id:'pb2', kp:'电路基础', type:'choice', difficulty:'medium',
    text:'如图电路，闭合开关S后灯L不亮。用电压表测ab间电压为0，bc间电压为电源电压。则故障可能是（  ）',
    options:['灯L短路','灯L断路','电阻R短路','电阻R断路'], answer:'B',
    explanation:'Ubc=电源电压→L两端电压等于电源电压，说明L以外的电路(Uab=0→导线)是通路→L可能断路。若L短路→Ubc=0。若R断路→Uab=电源电压。若R短路→不影响L。验证：L断路→电路中无电流→R两端无电压(Uab=0)，电压表测L两端=电源电压(Ubc=电源)。', source:'2026精练·电路故障' },
  { id:'pb3', kp:'物态变化', type:'fill', difficulty:'easy',
    text:'春天冰雪消融是____现象，夏天湿衣服晾干是____现象，秋天早晨草叶上的露珠是____现象，冬天玻璃窗上的冰花是____现象。（填物态变化名称）', options:null,
    answer:'熔化；汽化（蒸发）；液化；凝华',
    explanation:'冰雪消融:固态→液态=熔化(吸热)。湿衣晾干:液态→气态=汽化/蒸发(吸热)。露珠:水蒸气→液态=液化(放热)。冰花:水蒸气→固态=凝华(放热)。物态变化六种需全部掌握。', source:'2026精练·物态变化判断' },
  { id:'pb4', kp:'力学基础', type:'fill', difficulty:'medium',
    text:'小明重500N，站在水平地面上时双脚与地面接触面积约400cm²，则他对地面的压强为____Pa。若他单脚站立，压强变为____Pa。', options:null,
    answer:'1.25×10⁴；2.5×10⁴',
    explanation:'双脚时S=400cm²=0.04m²。p=F/S=500/0.04=12500Pa=1.25×10⁴Pa。单脚时S减半=0.02m²→p=500/0.02=25000Pa。压强与受力面积成反比。', source:'2026精练·压强计算' },
  { id:'pb5', kp:'电功率', type:'fill', difficulty:'medium',
    text:'标有"6V 3W"的小灯泡正常发光时的电阻为____Ω，通过它的电流为____A。若将它接在3V电源上，实际功率为____W（灯丝电阻不变）。', options:null,
    answer:'12；0.5；0.75',
    explanation:'R=U²/P=36/3=12Ω。I=P/U=3/6=0.5A。接3V:P实=U实²/R=9/12=0.75W。灯泡暗→因为实际电压小于额定电压。', source:'2026精练·实际功率' },
  { id:'pb6', kp:'压强浮力', type:'fill', difficulty:'medium',
    text:'一个质量为200g的苹果漂浮在水面上，它受到的浮力为____N，排开水的体积为____cm³。(g=10N/kg)', options:null,
    answer:'2；200',
    explanation:'漂浮→F浮=G=mg=0.2×10=2N。F浮=ρ水gV排→V排=2/(1000×10)=2×10⁻⁴m³=200cm³。', source:'2026精练·漂浮浮力' },
  { id:'pb7', kp:'电与磁', type:'choice', difficulty:'medium',
    text:'关于电动机和发电机，下列说法正确的是（  ）',
    options:['电动机利用电磁感应原理','发电机将电能转化为机械能','电动机将电能转化为机械能','发电机和电动机原理相同'], answer:'C',
    explanation:'电动机:电能→机械能，原理是通电导体在磁场中受力。发电机:机械能→电能，原理是电磁感应。两者原理不同、能量转化方向相反。', source:'2026精练·电动机发电机' },
  { id:'pb8', kp:'简单机械', type:'solution', difficulty:'medium',
    text:'工人用如图斜面将重600N的木箱推到1.5m高的车厢上，斜面长4m。\n(1)若斜面光滑，推力为多少？\n(2)若实际推力为300N，斜面的机械效率是多少？\n(3)木箱与斜面间的摩擦力为多少？',
    options:null,
    answer:'(1)225N；(2)75%；(3)75N',
    explanation:'(1)光滑:FL=Gh→F=600×1.5/4=225N。\n(2)实际F=300N:W有=Gh=600×1.5=900J。W总=Fs=300×4=1200J。η=900/1200=75%。\n(3)W额=W总-W有=1200-900=300J。f=W额/L=300/4=75N。\n【考点】斜面功/效率/摩擦力。额外功全部来自摩擦。', source:'2026精练·斜面效率' },
  { id:'pb9', kp:'电路基础', type:'fill', difficulty:'medium',
    text:'两个电阻R₁=6Ω和R₂=12Ω。串联后总电阻为____Ω，并联后总电阻为____Ω。若将它们并联接入6V电源，干路电流为____A。', options:null,
    answer:'18；4；1.5',
    explanation:'串联:R总=6+12=18Ω。并联:R总=6×12/(6+12)=72/18=4Ω。并联接6V:I=U/R总=6/4=1.5A。', source:'2026精练·串并联电阻' },
  { id:'pb10', kp:'光现象', type:'fill', difficulty:'easy',
    text:'光从空气斜射入水中，折射角____入射角（填"大于""小于"或"等于"）。若入射角增大，折射角也____。当光垂直射入水面时，折射角为____°。', options:null,
    answer:'小于；增大；0',
    explanation:'光从空气(光疏)斜射入水(光密)→折射角<入射角(向法线偏折)。入射角增大→折射角随之增大。垂直入射→入射角=0→折射角=0(光线方向不变)。', source:'2026精练·光的折射' }
);

// ═══ 化学补充 ═══
SUBJECTS.chemistry.questions.push(
  { id:'cb1', kp:'物质变化', type:'choice', difficulty:'easy',
    text:'下列生活中常见变化属于物理变化的是（  ）',
    options:['铁锅生锈','牛奶变酸','冰雪融化','食物腐败'], answer:'C',
    explanation:'冰雪融化只是状态改变(固态→液态)，无新物质生成，是物理变化。其余均有新物质生成→化学变化。', source:'2026精练·物理变化判断' },
  { id:'cb2', kp:'空气氧气', type:'fill', difficulty:'easy',
    text:'空气的成分按体积分数计算：氮气约占____%，氧气约占____%。空气中含量最多的气体是____。', options:null,
    answer:'78；21；氮气（N₂）',
    explanation:'干燥空气中N₂约78%，O₂约21%，稀有气体约0.94%，CO₂约0.03%。氮气含量最多。', source:'2026精练·空气成分' },
  { id:'cb3', kp:'金属', type:'fill', difficulty:'easy',
    text:'铁生锈是铁与____和____共同作用的结果。防止铁生锈的方法有____、____等。', options:null,
    answer:'氧气（O₂）；水（H₂O）；涂油；刷漆（或镀层/制成不锈钢等）',
    explanation:'铁锈蚀条件：铁+O₂+H₂O→铁锈(Fe₂O₃·xH₂O)。防锈原理：隔绝O₂或H₂O。方法：涂油漆、镀层、制成合金(不锈钢)等。', source:'2026精练·铁生锈条件' },
  { id:'cb4', kp:'酸碱盐', type:'choice', difficulty:'medium',
    text:'下列物质中，pH最小的是（  ）',
    options:['石灰水','食盐水','稀盐酸','苏打水'], answer:'C',
    explanation:'pH<7酸性。石灰水(Ca(OH)₂)碱性pH>7，食盐水(NaCl)中性pH≈7，稀盐酸(HCl)酸性pH<7(强酸pH≈1-2)，苏打水(Na₂CO₃)碱性pH>7。pH最小→酸性最强→稀盐酸。', source:'2026精练·pH判断' },
  { id:'cb5', kp:'水与溶液', type:'fill', difficulty:'medium',
    text:'20℃时NaCl的溶解度为36g。其含义是____。20℃时将40g NaCl加入100g水中，所得溶液为____（饱和/不饱和），溶质质量分数为____（精确到0.1%）。', options:null,
    answer:'20℃时100g水中最多溶解36g NaCl达到饱和；饱和；26.5%',
    explanation:'40g>36g→只能溶解36g(饱和)。ω=36/(100+36)×100%≈26.5%。注意：未溶解的4g不计入溶液质量。', source:'2026精练·溶解度计算' },
  { id:'cb6', kp:'酸碱盐', type:'choice', difficulty:'medium',
    text:'下列各组物质混合后，溶液质量增加的是（  ）',
    options:['铁片浸入CuSO₄溶液','锌粒加入稀盐酸','铜片浸入AgNO₃溶液','NaOH溶液与稀盐酸混合'], answer:'D',
    explanation:'A:Fe+CuSO₄→FeSO₄+Cu,每56g Fe进入溶液置换出64g Cu→溶液减重8g。B:Zn+2HCl→ZnCl₂+H₂↑,每65g Zn进入溶液放出2g H₂→溶液增重63g。C:Cu+2AgNO₃→Cu(NO₃)₂+2Ag,每64g Cu进入溶液置换出216g Ag→溶液减重152g。D:NaOH+HCl→NaCl+H₂O,无沉淀无气体→溶液质量不变。本题要求选增加：B方案正确。但B在安徽中考中"产生气体→溶液增量"需细算。\n正确答案为B。', source:'2026精练·溶液质量变化' },
  { id:'cb7', kp:'实验探究', type:'fill', difficulty:'medium',
    text:'量筒量取液体时，视线应与液体____保持水平。若仰视读数，读数值比实际体积____（偏大/偏小）。托盘天平称量时，砝码和药品放反且使用游码，称得质量比实际____。', options:null,
    answer:'凹液面最低处；偏小；偏大',
    explanation:'量筒:视线与凹液面最低处水平→读数正确。仰视→视线偏低→读数偏小(实际体积更大)。天平:左物右码正确。放反→物品质量=砝码-游码<砝码→实际质量<称量读数→称得偏大。', source:'2026精练·实验操作误差' },
  { id:'cb8', kp:'酸碱盐', type:'solution', difficulty:'medium',
    text:'有一包白色固体，可能含有NaCl、Na₂CO₃、Na₂SO₄、BaCl₂中的一种或几种。进行如下实验：\n①取样加水溶解，得到无色透明溶液；\n②滴加稀盐酸，产生能使石灰水变浑浊的气体；\n③滴加BaCl₂溶液，产生白色沉淀，加稀硝酸沉淀不溶解。\n(1)原白色固体中一定含有____，一定不含____；\n(2)写出步骤②的化学方程式____。',
    options:null,
    answer:'(1)Na₂CO₃和Na₂SO₄；BaCl₂（因为溶于水无沉淀→无BaCl₂与Na₂CO₃/Na₂SO₄共存）;NaCl可能含有。(2)Na₂CO₃+2HCl=2NaCl+H₂O+CO₂↑',
    explanation:'①无色透明→无不溶物→不能同时含BaCl₂和Na₂CO₃/Na₂SO₄。②产生CO₂→含Na₂CO₃→一定不含BaCl₂(否则①会生成BaCO₃沉淀)。③加BaCl₂产生不溶于稀硝酸的白色沉淀→BaSO₄→含Na₂SO₄。NaCl无法确定→可能含有。\n【考点】离子检验+物质推断。安徽化学常考推断题。', source:'2026精练·物质推断' },
  { id:'cb9', kp:'水与溶液', type:'choice', difficulty:'medium',
    text:'如图是KNO₃的溶解度曲线。下列说法正确的是（  ）',
    options:['KNO₃的溶解度随温度升高而减小','20℃时KNO₃溶液的溶质质量分数为31.6%','将60℃的饱和KNO₃溶液降温至20℃一定有晶体析出','40℃时100g KNO₃饱和溶液含KNO₃63.9g'], answer:'C',
    explanation:'KNO₃溶解度随温度升高而增大→A错。20℃时溶解度31.6g→饱和溶液ω=31.6/131.6≈24%≠31.6%→B错。降温→溶解度减小→饱和溶液析出晶体→C对。40℃时溶解度63.9g→100g水(非100g溶液)溶63.9g→D错。', source:'2026精练·溶解度曲线分析' },
  { id:'cb10', kp:'实验探究', type:'fill', difficulty:'medium',
    text:'做铁丝在氧气中燃烧实验时，集气瓶底要____。铁丝绕成螺旋状的目的是____。火柴的作用是____。', options:null,
    answer:'放少量水（或铺细沙）；增大铁丝受热面积（聚热）；引燃铁丝（提高温度至着火点）',
    explanation:'铁丝燃烧生成高温熔融物Fe₃O₄→掉落会炸裂瓶底→铺沙或加水保护。螺旋状→聚热使温度更容易达到着火点。火柴→先点燃火柴→火柴燃烧提供热量引燃铁丝。', source:'2026精练·铁丝燃烧实验' }
);

// ═══ 道法补充 ═══
SUBJECTS.politics.questions.push(
  { id:'zb1', kp:'成长与自我', type:'choice', difficulty:'easy',
    text:'"天行健，君子以自强不息。"这句古语告诉我们（  ）',
    options:['遇到困难就放弃','要自强不息不断超越自我','自强就是不需要他人帮助','每个人天生就是自强的人'], answer:'B',
    explanation:'自强是中华民族精神的重要内容。自强让青春奋进的步伐永不停息。', source:'2026精练·自强精神' },
  { id:'zb2', kp:'友谊与交往', type:'choice', difficulty:'easy',
    text:'与父母发生矛盾时，正确的做法是（  ）',
    options:['大吵大闹据理力争','不理不睬冷战到底','换位思考主动沟通','完全听从什么都答应'], answer:'C',
    explanation:'亲子冲突需要双方通过良好的互动沟通来解决。选择不伤害父母感情、不影响亲子关系的做法。', source:'2026精练·亲子沟通' },
  { id:'zb3', kp:'集体与法治', type:'choice', difficulty:'medium',
    text:'法律区别于道德等行为规范的最主要特征是（  ）',
    options:['由国家制定或认可','由国家强制力保证实施','对全体社会成员具有普遍约束力','规定公民的权利和义务'], answer:'B',
    explanation:'国家强制力（军队、警察、法庭、监狱等）是法律区别于道德、纪律等其他行为规范的最主要特征。', source:'2026精练·法律特征' },
  { id:'zb4', kp:'社会与规则', type:'choice', difficulty:'medium',
    text:'下列行为中属于一般违法行为的是（  ）',
    options:['持刀抢劫','贩卖毒品','闯红灯被罚款','故意杀人'], answer:'C',
    explanation:'闯红灯违反《道路交通安全法》→行政违法行为(一般违法)。持刀抢劫、贩卖毒品、故意杀人→触犯刑法→犯罪(严重违法行为)。', source:'2026精练·违法分类' },
  { id:'zb5', kp:'国家与制度', type:'choice', difficulty:'medium',
    text:'我国的根本政治制度是____，基本政治制度包括____、____、____。', options:null,
    answer:'人民代表大会制度；中国共产党领导的多党合作和政治协商制度；民族区域自治制度；基层群众自治制度',
    explanation:'根本政治制度=人民代表大会制度(八下)。三个基本政治制度:政协制度、民族区域自治、基层群众自治。注意区分"根本"和"基本"。', source:'2026精练·政治制度' },
  { id:'zb6', kp:'创新与发展', type:'choice', difficulty:'medium',
    text:'我国社会主要矛盾已经转化为（  ）',
    options:['人民日益增长的物质文化需要同落后的社会生产之间的矛盾','人民日益增长的美好生活需要和不平衡不充分的发展之间的矛盾','经济发展与环境保护之间的矛盾','城市与农村发展之间的矛盾'], answer:'B',
    explanation:'党的十九大提出：我国社会主要矛盾已转化为人民日益增长的美好生活需要和不平衡不充分的发展之间的矛盾。', source:'2026精练·主要矛盾' },
  { id:'zb7', kp:'文化与自信', type:'choice', difficulty:'easy',
    text:'中华文化的特点是（  ）',
    options:['源远流长、博大精深','独一无二、举世无双','开放包容、与时俱进','历史悠久、世界领先'], answer:'A',
    explanation:'源远流长(时间维度，五千年未曾中断)和博大精深(空间维度，内容丰富深厚)是中华文化两大特点。"独一无二""举世无双""世界领先"不是标准表述。', source:'2026精练·中华文化特点' },
  { id:'zb8', kp:'世界与中国', type:'choice', difficulty:'easy',
    text:'当今时代的主题是（  ）',
    options:['战争与革命','和平与发展','合作与竞争','对抗与冲突'], answer:'B',
    explanation:'和平与发展是当今时代的主题。注意区分：经济全球化和世界多极化是当今世界的发展趋势。', source:'2026精练·时代主题' },
  { id:'zb9', kp:'社会与规则', type:'solution', difficulty:'medium',
    text:'某中学开展"模拟政协"活动，学生撰写"提案"提交给政协委员。请谈谈这项活动的意义。',
    options:null,
    answer:'①有利于增强学生的民主意识和参政议政能力。②有利于学生了解我国的政治制度，加深对社会主义民主的认识。③有利于培养学生的社会责任感和主人翁意识。④有利于锻炼学生的调查研究、分析问题和解决问题的能力。⑤是学校开展法治教育和公民教育的重要实践形式。',
    explanation:'本题从"模拟政协"切入，考查民主参与意识。答题角度：知识层面（了解制度）+能力层面（锻炼能力）+情感层面（增强社会责任感）。', source:'2026精练·民主意识' },
  { id:'zb10', kp:'青春与情绪', type:'solution', difficulty:'medium',
    text:'考试前小明感到非常紧张焦虑。请运用"做情绪的主人"相关知识，给小明提出三条调节情绪的建议。',
    options:null,
    answer:'①改变认知评价——正确看待考试，认识到适度焦虑有利于发挥。②转移注意——适当进行体育锻炼或听音乐放松。③合理宣泄——找朋友或家人倾诉自己的压力。④放松训练——深呼吸、肌肉放松等缓解紧张。',
    explanation:'情绪调节方法（七下）：改变认知评价、转移注意、合理宣泄、放松训练。需结合具体情境给出可操作的建议。', source:'2026精练·情绪调节方法' }
);

console.log('[精选题库三] 全部加载');
})();
